// THIS CODE WAS GENERATED BY API SERVICE, IT WILL TAKE ERROR IF CHANGE IT!!!!
// if you found any error, please re-generate it by ~/apiscripts/typescript/
// Web foundation Service Api.
/* tslint:disable:max-classes-per-file */
/* tslint:disable:max-line-length */

import ItsApp from '@/generic/ItsApp';

export type Float = number;
export type Double = number;
export type Single = number;
export type Guid = string;
export type DateTime = string;
export type Char = string;
export type Decimal = number;
export type SByte = number;
export type Byte = number;
export type Int16 = number;
export type UInt16 = number;
export type Int32 = number;
export type UInt32 = number;
export type Int64 = number;
export type UInt64 = number;
export type String = string;
export type Boolean = boolean;
export type IHttpActionResult = any;

export interface CountModel {
  module_count: Int32;
}

export class BasicModule {
  constructor(private app: ItsApp) {}

  /** GET  */

  public GetCount(showProgress = true) {
    return this.app.request.get<CountModel>('module', 'count', null, {
      notShowProgress: !showProgress,
    });
  }
}
